---
langauge: c
env:
  - TRUBY=ruby-2.0.0-p648 OPENSSL=openssl-1.0.1d
  - TRUBY=ruby-2.3.0 OPENSSL=openssl-1.0.2f
  - TRUBY=jruby-9.0.0.0 OPENSSL=none
  - TRUBY=jruby-9.0.4.0 OPENSSL=none
install:
  - RUBY_URL=https://s3-eu-west-1.amazonaws.com/hetznerza/travis-ci/precise/no-rvm/${TRUBY}-${OPENSSL}.tar.gz
  - rvm implode --force
  - sudo mkdir -p /opt/rubies
  - curl ${RUBY_URL} | sudo tar -C /opt/rubies -xzf -
  - git clone https://github.com/postmodern/chruby.git
  - (cd chruby && sudo ./scripts/setup.sh)
  - chruby-exec ${TRUBY} -- ruby --version
  - chruby-exec ${TRUBY} -- gem install --no-ri --no-rdoc bundler
script:
  - chruby-exec ${TRUBY} -- ruby --version
  - chruby-exec ${TRUBY} -- bundle
  - chruby-exec ${TRUBY} -- bundle exec rake
